blank_issues_enabled: false
contact_links:
  - name: DeCleanup Rewards Support
    url: https://farcaster.xyz/miniapps/njiQzfqas3yN/decleanup-rewards
    about: Get help with the DeCleanup Rewards mini app

